version: '3'

services:
  tileserver:
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - "./test_data:/data"
  web:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - "./www:/usr/share/nginx/html:ro"